### ISSUE TITLE
Regarding Task 3

### ISSUE THREAD

**Issue by dinithiW** [common-workflow-lab/wdl-cwl-translator#1]
I have generated the Python3 parser code using the WDL grammar. Now I have 3 files, WdlV1_1Lexer.py,WdlV1_1Parser.py and WdlV1_1ParserListener.py.  I don't understand the contents of the files or how to use them for task 3. Any tips on how to get started?

**Comment by tetron** [comment]
Hi @dinithiW I've updated the README with more documentation links, please close the issue if those answer your question.
