### ISSUE TITLE
WDL `runtime.disks` with suffixes, WDL expressions

### ISSUE THREAD

**Issue by mr-c** [common-workflow-lab/wdl-cwl-translator#105]
Follow on to #95 

https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#disks

`<mount-point>`s should be accepted and their sizes included, but the mount points themselves won't appear in the CWL output as CWL has no concept of per-mountpoint persistent volumes and space reservation.

Example from the current tests:
https://github.com/broadinstitute/warp/blob/9ea4dc8ad4eca794ed336451fa8b23367132a820/tasks/broad/Qc.wdl#L37
> `disks: "local-disk " + disk_size + " HDD"`

`local-disk` is a Cromwell specific mount point, and so should be ignored.

The `HDD` disk type postfix is [Cromwell specific thing](https://cromwell.readthedocs.io/en/stable/RuntimeAttributes/#disks) and not part of OpenWDL, however we must tolerate it by ignoring it as well as `SDD`or `LOCAL` postfixes.

The correct translation of this example for CWL would be

``` cwl
hints:
  ResourceRequirement:
     outdirMin: $(((Math.ceil(inputs.input_bam.size) / 1024^3) + 20) / 1024)
```

https://www.commonwl.org/v1.2/CommandLineTool.html#ResourceRequirement

**Comment by Th3nn3ss** [comment]
```
outdirMin: $((Math.ceil((function(size_of=0){inputs.input_bam.path.forEach(function(element){
     if (element) {size_of += element.size}})}) / 1024^3)  + 20)/ 1024)
```
