### ISSUE TITLE
Explain how to run/test WDL files

### ISSUE THREAD

**Issue by mr-c** [common-workflow-lab/wdl-cwl-translator#2]
https://github.com/broadinstitute/cromwell

**Comment by geoffjentry** [comment]
@mr-c It might be better to point to/use [MiniWDL](https://github.com/chanzuckerberg/miniwdl) for these sorts of examples. MiniWDL is targeting the light weight, running locally, etc end of things and my understanding is that the Cromwell team is trying to move away from that as a use case they support

**Comment by mr-c** [comment]
We now link to the miniwdl documentation
