### ISSUE TITLE
WDL runtime requirement 'preemptible' not handled

### ISSUE THREAD

**Issue by dinithiW** [common-workflow-lab/wdl-cwl-translator#23]
Currently, the WDL runtime requirement ```preemptible``` is not translated by the convertor and only issues a warning when encountered. Unable to find a way to handle preemptible in CWL. 

https://github.com/broadinstitute/warp/blob/develop/tasks/broad/Qc.wdl#L39

**Comment by mr-c** [comment]
There isn't anything to map to anything in CWL, so a warning is good enough
