### ISSUE TITLE
Expression Placeholder Option 'true and false' is not handled

### ISSUE THREAD

**Issue by dinithiW** [common-workflow-lab/wdl-cwl-translator#25]
e.g. ~{true="--yes" false="--no" boolean_value}
https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#-expression-placeholder-options mentions that expression placeholder options are deprecated and will be removed in WDL 2.0.

https://github.com/biowdl/tasks/blob/develop/seqtk.wdl#L41 uses the mentioned expression placeholder option.

**Comment by mr-c** [comment]
Fixed in https://github.com/common-workflow-lab/wdl-cwl-translator/pull/37
