### ISSUE TITLE
Task 4

### ISSUE THREAD

**Issue by dinithiW** [common-workflow-lab/wdl-cwl-translator#3]
Is 'cwl_utils.parser_v1_2.CommandLineTool' mentioned in task 4 referring to the code given in line 6995 'class CommandLineTool(Process):' of https://github.com/common-workflow-language/cwl-utils/blob/main/cwl_utils/parser_v1_2.py ? Also, how do I get started with creating a CWL data structure?

**Comment by tetron** [comment]
Hi @dinithiW 

@mr-c just added an example of this:

https://github.com/common-workflow-language/cwl-utils/blob/main/create_cwl_from_objects.py

**Comment by dinithiW** [comment]
ok. So  what exactly needs to be done? Change the code in 'create_cwl_from_objects.py' to recreate https://github.com/common-workflow-language/cwl-utils/blob/main/testdata/md5sum.cwl ?

**Comment by tetron** [comment]
That's correct.

**Comment by dinithiW** [comment]
I have recreated a somewhat similar version of this file(https://github.com/common-workflow-language/cwl-utils/blob/main/testdata/md5sum.cwl). I can display the output to the terminal, but I'm having trouble saving it to a .cwl file. How do I approach this?

**Comment by mr-c** [comment]
> I have recreated a somewhat similar version of this file(https://github.com/common-workflow-language/cwl-utils/blob/main/testdata/md5sum.cwl). I can display the output to the terminal, but I'm having trouble saving it to a .cwl file. How do I approach this?

Can you open a draft PR so we can leave comments on your code? Much easier for us than guessing :-)

**Comment by dinithiW** [comment]
Hi! I tried making a PR, but I'm getting this error.
remote: Permission to common-workflow-lab/wdl-cwl-translator.git denied to dinithiW.
fatal: unable to access 'https://github.com/common-workflow-lab/wdl-cwl-translator.git/': The requested URL returned error: 403

I pushed some code to a local repository I have, and it worked fine. Is the error from my side?

**Comment by tetron** [comment]
Hi @dinithiW you should click on the "Fork" in upper-right corner of the page.  This will create your own personal copy of the git repository, which you can push to.  After you push, when you look at your fork, github will offer a "create pull request" button.

**Comment by dinithiW** [comment]
ok. I made the PR

**Comment by mr-c** [comment]
Great! Lets continue the conversation at https://github.com/common-workflow-lab/wdl-cwl-translator/pull/4
