### ISSUE TITLE
Expressions in input default values are not handled

### ISSUE THREAD

**Issue by dinithiW** [common-workflow-lab/wdl-cwl-translator#38]
Currently, expressions in integer inputs are not translated by the convertor and only issues a warning when encountered.

A WDL workflow containing integer input expressions can be found here. (https://github.com/biowdl/tasks/blob/develop/hisat2.wdl#L42)

**Comment by mr-c** [comment]
In CWL v1.2, can’t use expressions default value field
So convert such inputs to be optional (if not already) and then where we use the value of the input: if the input is missing (`null`) then compute the expression, otherwise use the provided value.

**Comment by mr-c** [comment]
Fixed in https://github.com/common-workflow-lab/wdl-cwl-translator/commit/9781f7b166165e2b06f5cecad49e58df6e24d0d9 (#150)
