### ISSUE TITLE
Array type outputs are not handled

### ISSUE THREAD

**Issue by dinithiW** [common-workflow-lab/wdl-cwl-translator#53]
Currently, array type outputs are not translated by the convertor.

A WDL workflow containing an array type output can be found here. (https://github.com/biowdl/tasks/blob/bc1bacf11498d2d30b85591cfccdcf71ef0966a5/rtg.wdl#L125)

**Comment by mr-c** [comment]
CWL `outputBinding.glob` also allows for arrays. If the WDL `Array[File]` references previous `File` outputs by name, then copy their `outputBinding.glob` values to the array `glob`.

**Comment by mr-c** [comment]
The example uses the `ceil` WDL function so #104 would need to be fixed first or at the same time
