### ISSUE TITLE
WDL function select_first() is not handled

### ISSUE THREAD

**Issue by dinithiW** [common-workflow-lab/wdl-cwl-translator#59]
Currently, the WDL function select_first() is not translated by the convertor. (https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#x-select_firstarrayx)

A WDL workflow containing select_first() function can be found here. (https://github.com/biowdl/tasks/blob/develop/bwa.wdl#L82)

**Comment by Th3nn3ss** [comment]
Is there a javascript equivalent for the WDL `select_first()` function?

**Comment by Th3nn3ss** [comment]
could I use the `find` function? 

Say, in the case of the example provided in (https://github.com/biowdl/tasks/blob/develop/bwa.wdl#L82):
`memory: "~{select_first([memoryGb, estimatedMemoryGb])}G"` would be converted to 
`memory: "${[memoryGb, estimatedMemoryGb].find(memory => moemory != None)}G"`

**Comment by kinow** [comment]
Hi @Th3nn3ss 

I think in JavaScript it would have to use strings `['memoryGb', 'estimatedMemoryGb']`. And the Python `None` does not exist in JavaScript. So probably treat it as `null` or `undefined` (or check if the None mentioned in the [WDL spec](https://github.com/openwdl/wdl/blob/main/versions/development/SPEC.md#x-select_firstarrayx) should be treated differently in the wdl-cwl-translator.)

Bruno

**Comment by Th3nn3ss** [comment]
> Hi @Th3nn3ss
> 
> I think in JavaScript it would have to use strings `['memoryGb', 'estimatedMemoryGb']`, unless these two are variales declared previously. And the Python `None` does not exist in JavaScript, so maybe test for `null` and `undefined` (or check if the None mentioned in the [WDL spec](https://github.com/openwdl/wdl/blob/main/versions/development/SPEC.md#x-select_firstarrayx) should be treated differently in the wdl-cwl-translator.)
> 
> Bruno

OK. 
The WDL documentation actually says it returns the first non-`None` value of an `Array` with optional values. So I have to find a way for a `None` to be treated as a Javascript `null' so it can return the appropriate error message when the expression isn't successful. Errors like `error! array contains only None values`

**Comment by mr-c** [comment]
> > Hi @Th3nn3ss
> > 
> > I think in JavaScript it would have to use strings `['memoryGb', 'estimatedMemoryGb']`, unless these two are variales declared previously. And the Python `None` does not exist in JavaScript, so maybe test for `null` and `undefined` (or check if the None mentioned in the [WDL spec](https://github.com/openwdl/wdl/blob/main/versions/development/SPEC.md#x-select_firstarrayx) should be treated differently in the wdl-cwl-translator.)
> > 
> > Bruno
> 
> OK. 
> The WDL documentation actually says it returns the first non-`None` value of an `Array` with optional values. So I have to find a way for a `None` to be treated as a Javascript `null` so it can return the appropriate error message when the expression isn't successful. Errors like `error! array contains only None values`

In this case the WDL `None` will be a CWL/ECMAScript `null`. Check the existing code in `main.py` to see how `null`/existence checks are currently handled.

**Comment by mr-c** [comment]
> Hi @Th3nn3ss 
> 
> I think in JavaScript it would have to use strings `['memoryGb', 'estimatedMemoryGb']`, unless these two are variales declared previously. And the Python `None` does not exist in JavaScript, so maybe test for `null` and `undefined` (or check if the None mentioned in the [WDL spec](https://github.com/openwdl/wdl/blob/main/versions/development/SPEC.md#x-select_firstarrayx) should be treated differently in the wdl-cwl-translator.)
> 
> Bruno

`memoryGb` is an optional input in this example, so it can be referred to as `inputs.memoryGb`.

`estimatedMemoryGb` is a "WDL declaration" that isn't bound to any input, so you may want to find another example or simplify the given example for testing.

https://github.com/common-workflow-lab/wdl-cwl-translator/issues/32

**Comment by Th3nn3ss** [comment]
From the sample (https://github.com/biowdl/tasks/blob/develop/bwa.wdl#L82), the `select_first()` function wasn't just used for getting the memory, it's also used here https://github.com/biowdl/tasks/blob/933e473d9484f5003c98e9c647ac5eba0893f4c3/bwa.wdl#L48

How do I capture it for every case where it appears?

**Comment by Th3nn3ss** [comment]
Is this the required output
`ramMin: ${[inputs.memoryGb].find(mem => mem !== null)}G`

**Comment by mr-c** [comment]
Fixed in #150
