### ISSUE TITLE
Workflow imports are not handled

### ISSUE THREAD

**Issue by dinithiW** [common-workflow-lab/wdl-cwl-translator#71]
Currently workflow imports of WDL documents are not translated. 
A workflow using imports can be found here: https://github.com/broadinstitute/warp/blob/b3f5c898d1b535aaca8dc9e9f4223697a7a0a9a9/pipelines/skylab/smartseq2_single_sample/SmartSeq2SingleSample.wdl#L3

**Comment by mr-c** [comment]
The example above uses `select_first`, so #59 would have to be fixed first or at the same time
