### ISSUE TITLE
WDL structs are not handled

### ISSUE THREAD

**Issue by dinithiW** [common-workflow-lab/wdl-cwl-translator#72]
Currently, WDL specific custom compound type ```struct``` is not translated by the translator (https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#custom-types-structs)

In WDL documents, after the definition of these structs, they can be referenced in the input, output and command sections. A workflow using ```struct``` type is shown in the this link. https://github.com/broadinstitute/warp/blob/b3f5c898d1b535aaca8dc9e9f4223697a7a0a9a9/pipelines/skylab/build_indices/BuildIndices.wdl#L3

Referencing in input section: https://github.com/broadinstitute/warp/blob/b3f5c898d1b535aaca8dc9e9f4223697a7a0a9a9/pipelines/skylab/build_indices/BuildIndices.wdl#L52
Referencing in output section: https://github.com/broadinstitute/warp/blob/b3f5c898d1b535aaca8dc9e9f4223697a7a0a9a9/pipelines/skylab/build_indices/BuildIndices.wdl#L126
Referencing in command section: https://github.com/broadinstitute/warp/blob/b3f5c898d1b535aaca8dc9e9f4223697a7a0a9a9/pipelines/skylab/build_indices/BuildIndices.wdl#L68

**Comment by mr-c** [comment]
For CWL use https://www.commonwl.org/v1.2/CommandLineTool.html#CommandInputRecordSchema , https://www.commonwl.org/v1.2/CommandLineTool.html#CommandOutputRecordSchema for CommandLineTools and https://www.commonwl.org/v1.2/Workflow.html#InputRecordSchema , https://www.commonwl.org/v1.2/Workflow.html#OutputRecordSchema for workflows

Conversion of one of the examples:
https://github.com/broadinstitute/warp/blob/b3f5c898d1b535aaca8dc9e9f4223697a7a0a9a9/pipelines/skylab/build_indices/BuildIndices.wdl#L3
``` cwl
type:
   type: record
   items:
      - id: genome_fa
        type: File
      - id: annotation_gtf
        type: File
```
