### ISSUE TITLE
WDL Workflow task calls are not handled

### ISSUE THREAD

**Issue by dinithiW** [common-workflow-lab/wdl-cwl-translator#73]
Currently, task calls in WDL workflows are not handled. (https://github.com/openwdl/wdl/blob/34cd5a849c3b8b89b24f422f1e7ca22656210be9/versions/1.1/SPEC.md#call-statement)

A workflow using task calls are given in this workflow (https://github.com/broadinstitute/warp/blob/b3f5c898d1b535aaca8dc9e9f4223697a7a0a9a9/pipelines/cemba/build_cemba_references/BuildCembaReferences.wdl#L10)

**Comment by mr-c** [comment]
Please only close this by adding https://github.com/broadinstitute/warp/blob/b3f5c898d1b535aaca8dc9e9f4223697a7a0a9a9/pipelines/cemba/build_cemba_references/BuildCembaReferences.wdl#L10 to the tests :-)
