### ISSUE TITLE
stdout() is not handled

### ISSUE THREAD

**Issue by dinithiW** [common-workflow-lab/wdl-cwl-translator#75]
Currently, stdout() is not handled by the translator. (https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#file-stdout)

A workflow using stdout() in outputs is given in this workflow (https://github.com/biowdl/tasks/blob/bc1bacf11498d2d30b85591cfccdcf71ef0966a5/transcriptclean.wdl#L89)

**Comment by dinithiW** [comment]
I am working on this issue now using the workflow mentioned previously. How can I make stdout as the type as shown in the third example here. https://www.commonwl.org/v1.0/CommandLineTool.html#stdout @mr-c

**Comment by mr-c** [comment]
``` python
cwl.CommandOutputParameter(id="an_output_name" type="stdout")
```
