### ISSUE TITLE
WDL `command` section: Consider a more object-oriented approach for WDL function

### ISSUE THREAD

**Issue by mr-c** [common-workflow-lab/wdl-cwl-translator#91]
(to be done after the issues in https://github.com/common-workflow-lab/wdl-cwl-translator/milestone/1 are done)

For processing of the WDL `command` section and the functions inside the WDL Expression Placeholders, our current approach is fragile and starting to get messy.

(which is totally fine, it got us this far!)

Next up is nesting functions, like [`if..then..else`](https://github.com/common-workflow-lab/wdl-cwl-translator/issues/74), and nesting existing functions.

So we need to come up with a plan that will produce more manageable and flexible code.

Related

#112 
#109

**Comment by Th3nn3ss** [comment]
I am guessing that using the `miniwdl WDL objects` replaces the need for the following implementation in the current `convert(workflow)` function:

```
def convert(workflow: str) -> str:
    """Generate a CWL object to match "cat-tool.cwl"."""
    f = open(workflow)
    text = InputStream(f.read())
    lexer = WdlV1_1Lexer(text)
    stream = CommonTokenStream(lexer)
    parser = WdlV1_1Parser(stream)
    tree = parser.document()  # type: ignore

    # create WdlV1_1ParserVisitor object and return all inputs, outputs, etc
    ast = WdlV1_1ParserVisitor()  # type: ignore
    ```

**Comment by mr-c** [comment]
@Th3nn3ss Yep!

**Comment by Th3nn3ss** [comment]
how does `cwltool` create a new WorkFlow object? is there like a detailed documentation other than the (user guide)[https://www.commonwl.org/user_guide/21-1st-workflow/index.html]

**Comment by Th3nn3ss** [comment]
I guess this is it https://github.com/common-workflow-language/cwl-utils/blob/64b08c52674af250ef51a8597683528eb939416a/cwl_utils/parser/cwl_v1_2.py#L12530

**Comment by mr-c** [comment]
> how does `cwltool` create a new WorkFlow object?

`cwltool` does not use `cwl-utils`.

**Comment by Th3nn3ss** [comment]
The converted cwl files using the OOP paradigm are expected to still be like a reproduction of the current files in test/cwl_files, right?

**Comment by mr-c** [comment]
@Th3nn3ss There could be formatting and ordering differences.

If there are large formatting differences, using `make cwltest` is helpful as it tests the functionality, not the exact bitstream.

**Comment by Th3nn3ss** [comment]
What is the best way to get all inputs using miniWDL (both declared and un-declared inputs)

**Comment by mr-c** [comment]
> What is the best way to get all inputs using miniWDL (both declared and un-declared inputs)

I don't know, I've never tried. What does Janis do?

https://github.com/PMCC-BioinformaticsCore/janis-core/blob/714eab7347edccffd7656876bf92305ae63954d3/janis_core/ingestion/fromwdl.py#L38

**Comment by Th3nn3ss** [comment]
It uses WDL.Task.inputs which is a list of all declared inputs within a task.

Then it uses the WDL.Tree.Decl method to add more inputs within a Workflow. Am still going through the code base though.. I just thought maybe there was a more straightforward way.

**Comment by Th3nn3ss** [comment]
I might have to install to try out Janis and miniWDL. I will do some biopsy on the code base to understand the inner workings.

**Comment by kinow** [comment]
Related

#112 
#109

**Comment by mr-c** [comment]
This was completed in #135 ; woo-hoo!
