### ISSUE TITLE
support WDL's `runtime.disks` using fixed numeric values

### ISSUE THREAD

**Issue by mr-c** [common-workflow-lab/wdl-cwl-translator#95]
https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#disks

https://www.commonwl.org/v1.2/CommandLineTool.html#ResourceRequirement

To test, edit our copy of [`CollectQualityYieldMetrics`](https://github.com/common-workflow-lab/wdl-cwl-translator/blob/main/wdl2cwl/tests/wdl_files/CollectQualityYieldMetrics.wdl) , and replace the `disks` entry with `disks: 40`.

Once this is implemented you'll need to comment out the other `disks` entries in the other WDL files until we add support for this pre-OpenWDL 1.1 syntax that they use

```
$ git grep disks: -- wdl2cwl/tests/wdl_files/
wdl2cwl/tests/wdl_files/CollectQualityYieldMetrics.wdl:    disks: "local-disk " + disk_size + " HDD"
wdl2cwl/tests/wdl_files/CollectReadgroupBamQualityMetrics.wdl:    disks: "local-disk " + disk_size + " HDD"
wdl2cwl/tests/wdl_files/TrimAdapters.wdl:    #disks: "local-disk ${disk} HDD"
wdl2cwl/tests/wdl_files/UmiCorrection.wdl:        #disks: "local-disk ${disk} HDD"
wdl2cwl/tests/wdl_files/read_string_cornercase.wdl:        disks: "local-disk ${required_disk} HDD"
wdl2cwl/tests/wdl_files/validateOptimus_1.wdl:        disks: "local-disk ${required_disk} HDD"
wdl2cwl/tests/wdl_files/validateOptimus_2.wdl:       disks: "local-disk ${required_disk} HDD"
wdl2cwl/tests/wdl_files/validateOptimus_3.wdl:        disks: "local-disk ${required_disk} HDD"
wdl2cwl/tests/wdl_files/validateOptimus_4.wdl:        disks: "local-disk ${required_disk} HDD"
wdl2cwl/tests/wdl_files/validateOptimus_5.wdl:    disks: "local-disk ${required_disk} HDD"
```

**Comment by RaOneG** [comment]
Hey @mr-c,
I submitted I [pull request](https://github.com/common-workflow-lab/wdl-cwl-translator/pull/100), can you take a look, please. and let me know if I went in the right direction?
