### ISSUE TITLE
Support multiple tasks in the same WDL pipeline

### ISSUE THREAD

**Issue by kinow** [common-workflow-lab/wdl-cwl-translator#99]
Hi,

In #97 , the pull request is handling WDL structs. Which is almost done now.

For writing the tests, I tried running the generated CWL workflow (didn't have a WDL runner yet). First I had an issue with runtime requirements (#98 ). But after I manually fixed it, then the next issue was a bit more enigmatic.

```
...
test.cwl:133:5: object id `test.cwl#BuildIntervalList/refflat` previously defined
test.cwl:137:5: object id `test.cwl#BuildIntervalList/interval_list` previously defined
test.cwl:54:5: object id `test.cwl#BuildIntervalList/genome_fa` previously defined
ERROR Tool definition failed validation:
test.cwl:3:1: Field name gtf_version already in use.
```

I thought it weird to see an error about `gtf_version`, I was sure it was only used once per task. Then I realized what was going on, after I saw the list of inputs with lots of types/fields.

From what I understood, the translator visits the generated AST and accumulates the types found. But I think it is accumulating all the types, of all the tasks in the warp BuildIndices pipeline, that contains one workflow that calls many tasks.

@mr-c I could be saying something really silly here, but basically I think the translator at the moment only works with WDL that contain a single task? I had a look at a handful of files in `tests/wdl_files`, and each file contained a single `Task` with input/output.

Cheers
Bruno

**Comment by kinow** [comment]
@Th3nn3ss I knew I had seen something about not supporting multiple tasks! :smile:

**Comment by mr-c** [comment]
This was done in https://github.com/common-workflow-lab/wdl-cwl-translator/pull/136 !
